/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups/$groupId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRoute
  '/friends': typeof AppFriendsRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups/': typeof AppGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRoute
  '/friends': typeof AppFriendsRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups': typeof AppGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/friends'
    | '/overview'
    | '/settings'
    | '/groups/$groupId'
    | '/api/auth/$'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/friends'
    | '/overview'
    | '/settings'
    | '/groups/$groupId'
    | '/api/auth/$'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/calendar'
    | '/_app/friends'
    | '/_app/overview'
    | '/_app/settings'
    | '/_app/groups/$groupId'
    | '/api/auth/$'
    | '/_app/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
